# Section 504 - BUILDING HEIGHT AND NUMBER OF STORIES

In [6]:
from IPython.display import Markdown, display
passed504 = None

In [7]:
def passedMessage(passed):     
    if passed is True:
        result = "Passed"
    elif passed is False:
        result = "Failed"
    else:
        result = "Not tested"
        
    message = f"This section is considered: {result}."
    display(Markdown(message))

passedMessage(passed504)
message = f"This section does not have any direct requirements to verify. Please refer to the subsections for analysis results."
display(Markdown(message))

This section is considered: Not tested.

This section does not have any direct requirements to verify. Please refer to the subsections for analysis results.

# Section 504.2 - Mixed occupancy
## Building Code
`In a building containing mixed occupancies in accordance with Section 508, no individual occupancy shall exceed the height and number of story limits specified in this section for the applicable occupancies.`

In [9]:
passed5042 = None
passedMessage(passed5042)
if passed5042 is True:
    result = "No individual occupancy exceeded"
elif passed5042 is False:
    result = "Individual occupancy(ies) exceeded"
else: 
    result = "Test indivual occupancy exceeds"
    
message = f"{result} the height and number of story limits specified in this section for the applicable occupancies."
display(Markdown(message))

This section is considered: Not tested.

Test indivual occupancy exceeds the height and number of story limits specified in this section for the applicable occupancies.

In [62]:
table_504_3 = {
    "A, A-2, A-3, B, E, F, M, S, U": {
        "NS": {
            "Type I": {"A": "UL", "B": 160},
            "Type II": {"A": 65, "B": 55},
            "Type III": {"A": 65, "B": 55},
            "Type IV": {"HT": 65},
            "Type V": {"A": 50, "B": 40},
        },
        "S": {
            "Type I": {"A": "UL", "B": 180},
            "Type II": {"A": 85, "B": 75},
            "Type III": {"A": 85, "B": 75},
            "Type IV": {"HT": 85},
            "Type V": {"A": 70, "B": 60},
        },
    },
    "H-1, H-2, H-3, H-5": {
        "NS": {
            "Type I": {"A": "UL", "B": 160},
            "Type II": {"A": 65, "B": 55},
            "Type III": {"A": 65, "B": 55},
            "Type IV": {"HT": 65},
            "Type V": {"A": 50, "B": 40},
        },
        "S": {
            "Type I": {"A": "UL", "B": 160},
            "Type II": {"A": 65, "B": 55},
            "Type III": {"A": 65, "B": 55},
            "Type IV": {"HT": 65},
            "Type V": {"A": 50, "B": 40},
        },
    },
    "H-4": {
        "NS": {
            "Type I": {"A": "UL", "B": 160},
            "Type II": {"A": 65, "B": 55},
            "Type III": {"A": 65, "B": 55},
            "Type IV": {"HT": 65},
            "Type V": {"A": 50, "B": 40},
        },
        "S": {
            "Type I": {"A": "UL", "B": 180},
            "Type II": {"A": 85, "B": 75},
            "Type III": {"A": 85, "B": 75},
            "Type IV": {"HT": 85},
            "Type V": {"A": 70, "B": 60},
        },
    },
    "I-1 Condition 1, I-3": {
        "NS": {
            "Type I": {"A": "UL", "B": 160},
            "Type II": {"A": 65, "B": 55},
            "Type III": {"A": 65, "B": 55},
            "Type IV": {"HT": 65},
            "Type V": {"A": 50, "B": 40},
        },
        "S": {
            "Type I": {"A": "UL", "B": 180},
            "Type II": {"A": 85, "B": 75},
            "Type III": {"A": 85, "B": 75},
            "Type IV": {"HT": 85},
            "Type V": {"A": 70, "B": 60},
        },
    },
    "I-1 Condition 2, I-2": {
        "NS": {
            "Type I": {"A": "UL", "B": 160},
            "Type II": {"A": 65, "B": 55},
            "Type III": {"A": 65, "B": 55},
            "Type IV": {"HT": 65},
            "Type V": {"A": 50, "B": 40},
        },
        "S": {
            "Type I": {"A": "UL", "B": 180},
            "Type II": {"A": 85, "B": 55},
            "Type III": {"A": 65, "B": 55},
            "Type IV": {"HT": 65},
            "Type V": {"A": 50, "B": 40},
        },
    },
    "I-4": {
        "NS": {
            "Type I": {"A": "UL", "B": 160},
            "Type II": {"A": 65, "B": 55},
            "Type III": {"A": 65, "B": 55},
            "Type IV": {"HT": 65},
            "Type V": {"A": 50, "B": 40},
        },
        "S": {
            "Type I": {"A": "UL", "B": 180},
            "Type II": {"A": 85, "B": 75},
            "Type III": {"A": 85, "B": 75},
            "Type IV": {"HT": 85},
            "Type V": {"A": 70, "B": 60},
        },
    },
    "R, R-1": {
        "NS": {
            "Type I": {"A": "UL", "B": 160},
            "Type II": {"A": 65, "B": 55},
            "Type III": {"A": 65, "B": 55},
            "Type IV": {"HT": 65},
            "Type V": {"A": 50, "B": 40},
        },
        "S13R": {
            "Type I": {"A": 60, "B": 60},
            "Type II": {"A": 60, "B": 60},
            "Type III": {"A": 60, "B": 60},
            "Type IV": {"HT": 60},
            "Type V": {"A": 60, "B": 60},
        },
        "S": {
            "Type I": {"A": "UL", "B": 180},
            "Type II": {"A": 85, "B": 75},
            "Type III": {"A": 85, "B": 75},
            "Type IV": {"HT": 85},
            "Type V": {"A": 70, "B": 60},
        },
    },
}

In [83]:
table_504_4 = {
    "A-1": {
        "NS": {
            "Type I": {"A": "UL", "B": 5},
            "Type II": {"A": 3, "B": 2},
            "Type III": {"A": 3, "B": 2},
            "Type IV": {"HT": 3},
            "Type V": {"A": 2, "B": 1}
        },
        "S": {
            "Type I": {"A": "UL", "B": 6},
            "Type II": {"A": 4, "B": 3},
            "Type III": {"A": 4, "B": 3},
            "Type IV": {"HT": 4},
            "Type V": {"A": 3, "B": 2}
        }
    },
    "A-2": {
        "NS": {
            "Type I": {"A": "UL", "B": 11},
            "Type II": {"A": 3, "B": 2},
            "Type III": {"A": 3, "B": 2},
            "Type IV": {"HT": 3},
            "Type V": {"A": 2, "B": 1}
        },
        "S": {
            "Type I": {"A": "UL", "B": 12},
            "Type II": {"A": 4, "B": 3},
            "Type III": {"A": 4, "B": 3},
            "Type IV": {"HT": 4},
            "Type V": {"A": 3, "B": 2}
        }
    },
    "A-3": {
        "NS": {
            "Type I": {"A": "UL", "B": 11},
            "Type II": {"A": 3, "B": 2},
            "Type III": {"A": 3, "B": 2},
            "Type IV": {"HT": 3},
            "Type V": {"A": 2, "B": 1}
        },
        "S": {
            "Type I": {"A": "UL", "B": 12},
            "Type II": {"A": 4, "B": 3},
            "Type III": {"A": 4, "B": 3},
            "Type IV": {"HT": 4},
            "Type V": {"A": 3, "B": 2}
        }
    },
    "A-4": {
        "NS": {
            "Type I": {"A": "UL", "B": 11},
            "Type II": {"A": 3, "B": 2},
            "Type III": {"A": 3, "B": 2},
            "Type IV": {"HT": 3},
            "Type V": {"A": 2, "B": 1}
        },
        "S": {
            "Type I": {"A": "UL", "B": 12},
            "Type II": {"A": 4, "B": 3},
            "Type III": {"A": 4, "B": 3},
            "Type IV": {"HT": 4},
            "Type V": {"A": 3, "B": 2}
        }
    },
    "A-5": {
        "NS": {
            "Type I": {"A": "UL", "B": "UL"},
            "Type II": {"A": "UL", "B": "UL"},
            "Type III": {"A": "UL", "B": "UL"},
            "Type IV": {"HT": "UL"},
            "Type V": {"A": "UL", "B": "UL"}
            },
        "S": {
            "Type I": {"A": "UL", "B": "UL"},
            "Type II": {"A": "UL", "B": "UL"},
            "Type III": {"A": "UL", "B": "UL"},
            "Type IV": {"HT": "UL"},
            "Type V": {"A": "UL", "B": "UL"}
            }
    },
    "B": {
        "NS": {
            "Type I": {"A": "UL", "B": 11},
            "Type II": {"A": 5, "B": 3},
            "Type III": {"A": 5, "B": 3},
            "Type IV": {"HT": 5},
            "Type V": {"A": 3, "B": 2}
        },
        "S": {
            "Type I": {"A": "UL", "B": 12},
            "Type II": {"A": 6, "B": 4},
            "Type III": {"A": 6, "B": 4},
            "Type IV": {"HT": 6},
            "Type V": {"A": 4, "B": 3}
        }
    },
    "E": {
        "NS": {
            "Type I": {"A": "UL", "B": 5},
            "Type II": {"A": 3, "B": 2},
            "Type III": {"A": 3, "B": 2},
            "Type IV": {"HT": 3},
            "Type V": {"A": 2, "B": 1}
        },
        "S": {
            "Type I": {"A": "UL", "B": 6},
            "Type II": {"A": 4, "B": 3},
            "Type III": {"A": 4, "B": 3},
            "Type IV": {"HT": 4},
            "Type V": {"A": 2, "B": 2}
        }
    },
    "F-1": {
        "NS": {
            "Type I": {"A": 11, "B": 4},
            "Type II": {"A": 2, "B": 2},
            "Type III": {"A": 3, "B": 2},
            "Type IV": {"HT": 2},
            "Type V": {"A": 1, "B": 1}
        },
        "S": {
            "Type I": {"A": 12, "B": 5},
            "Type II": {"A": 3, "B": 3},
            "Type III": {"A": 4, "B": 3},
            "Type IV": {"HT": 3},
            "Type V": {"A": 2, "B": 2}
        }
    },
    "F-2": {
        "NS": {
            "Type I": {"A": 11, "B": 5},
            "Type II": {"A": 3, "B": 3},
            "Type III": {"A": 4, "B": 3},
            "Type IV": {"HT": 4},
            "Type V": {"A": 3, "B": 2}
        },
        "S": {
            "Type I": {"A": 12, "B": 6},
            "Type II": {"A": 4, "B": 4},
            "Type III": {"A": 5, "B": 4},
            "Type IV": {"HT": 5},
            "Type V": {"A": 4, "B": 3}
        }
    },
    "H-1": {
        "NS": {"Type I": {"A": 1}},
        "S": {"Type I": {"A": "NP"}}
    },
    "H-2": {
        "NS": {
            "Type I": {"A": 3},
            "Type II": {"A": 2},
            "Type III": {"A": 1},
            "Type IV": {"HT": 2},
            "Type V": {"A": 1}
        },
        "S": {"Type I": {"A": "NP"}}
    },
    "H-3": {
        "NS": {
            "Type I": {"A": 6},
            "Type II": {"A": 4},
            "Type III": {"A": 2},
            "Type IV": {"HT": 4},
            "Type V": {"A": 2}
        },
        "S": {"Type I": {"A": "NP"}}
    },
    "H-4": {
        "NS": {
            "Type I": {"A": 7},
            "Type II": {"A": 5},
            "Type III": {"A": 3},
            "Type IV": {"HT": 5},
            "Type V": {"A": 3}
        },
        "S": {
            "Type I": {"A": 8},
            "Type II": {"A": 6},
            "Type III": {"A": 4},
            "Type IV": {"HT": 6},
            "Type V": {"A": 4}
        }
    },
    "H-5": {
        "NS": {
            "Type I": {"A": 4},
            "Type II": {"A": 4},
            "Type III": {"A": 3},
            "Type IV": {"HT": 3},
            "Type V": {"A": 3}
        },
        "S": {"Type I": {"A": "NP"}}
    },
    "I-1 Condition 1": {
        "NS": {
            "Type I": {"A": 9, "B": 4},
            "Type II": {"A": 4, "B": 3},
            "Type III": {"A": 4, "B": 3},
            "Type IV": {"HT": 4},
            "Type V": {"A": 3, "B": 2}
        },
        "S": {
            "Type I": {"A": 10, "B": 5},
            "Type II": {"A": 5, "B": 4},
            "Type III": {"A": 5, "B": 4},
            "Type IV": {"HT": 5},
            "Type V": {"A": 4, "B": 3}
        }
    },
    "I-1 Condition 2": {
        "NS": {
            "Type I": {"A": 9, "B": 4},
            "Type II": {"A": 4, "B": 3},
            "Type III": {"A": 4, "B": 3},
            "Type IV": {"HT": 4},
            "Type V": {"A": 3, "B": 2}
        },
        "S": {"Type I": {"A": 10}}
    },
    "I-2": {
        "NS": {
            "Type I": {"A": 4},
            "Type II": {"A": 2},
            "Type III": {"A": 1},
            "Type IV": {"HT": "NP"},
            "Type V": {"A": 1}
        },
        "S": {"Type I": {"A": 5}}
    },
    "I-3": {
        "NS": {
            "Type I": {"A": 4},
            "Type II": {"A": 2},
            "Type III": {"A": 1},
            "Type IV": {"HT": 2},
            "Type V": {"A": 2}
        },
        "S": {
            "Type I": {"A": 5},
            "Type II": {"A": 3},
            "Type III": {"A": 2},
            "Type IV": {"HT": 3},
            "Type V": {"A": 3}
        }
    },
    "I-4": {
        "NS": {
            "Type I": {"A": 5},
            "Type II": {"A": 3},
            "Type III": {"A": 2},
            "Type IV": {"HT": 3},
            "Type V": {"A": 1}
        },
        "S": {
            "Type I": {"A": 6},
            "Type II": {"A": 4},
            "Type III": {"A": 3},
            "Type IV": {"HT": 4},
            "Type V": {"A": 2}
        }
    },
    "M": {
        "NS": {
            "Type I": {"A": 11},
            "Type II": {"A": 4},
            "Type III": {"A": 2},
            "Type IV": {"HT": 4},
            "Type V": {"A": 3}
        },
        "S": {
            "Type I": {"A": 12},
            "Type II": {"A": 5},
            "Type III": {"A": 3},
            "Type IV": {"HT": 5},
            "Type V": {"A": 4}
        }
    },
    "R-1": {
        "NS": {
            "Type I": {"A": "UL", "B": 11},
            "Type II": {"A": 4, "B": 4},
            "Type III": {"A": 4, "B": 4},
            "Type IV": {"HT": 4},
            "Type V": {"A": 3, "B": 2}
        },
        "S13R": {
            "Type I": {"A": 4, "B": 4},
            "Type II": {"A": 4, "B": 4},
            "Type III": {"A": 4, "B": 4},
            "Type IV": {"HT": 4},
            "Type V": {"A": 4, "B": 3}
        },
        "S": {
            "Type I": {"A": "UL", "B": 12},
            "Type II": {"A": 5, "B": 5},
            "Type III": {"A": 5, "B": 5},
            "Type IV": {"HT": 5},
            "Type V": {"A": 4, "B": 3}
        }
    },
    "R-2": {
        "NS": {
            "Type I": {"A": 11, "B": 4},
            "Type II": {"A": 4},
            "Type III": {"A": 4},
            "Type IV": {"HT": 4},
            "Type V": {"A": 3}
        },
        "S": {
            "Type I": {"A": 12, "B": 5},
            "Type II": {"A": 5},
            "Type III": {"A": 5},
            "Type IV": {"HT": 5},
            "Type V": {"A": 4}
        }
    },
    "R-3": {
        "NS": {
            "Type I": {"A": 11, "B": 4},
            "Type II": {"A": 4},
            "Type III": {"A": 4},
            "Type IV": {"HT": 4},
            "Type V": {"A": 3}
        },
        "S": {
            "Type I": {"A": 12, "B": 5},
            "Type II": {"A": 5},
            "Type III": {"A": 5},
            "Type IV": {"HT": 5},
            "Type V": {"A": 4}
        }
    },
    "R-4": {
        "NS": {
            "Type I": {"A": 11, "B": 4},
            "Type II": {"A": 4},
            "Type III": {"A": 4},
            "Type IV": {"HT": 4},
            "Type V": {"A": 3}
        },
        "S": {
            "Type I": {"A": 12, "B": 5},
            "Type II": {"A": 5},
            "Type III": {"A": 5},
            "Type IV": {"HT": 5},
            "Type V": {"A": 4}
        }
    },
    "S-1": {
        "NS": {
            "Type I": {"A": 11},
            "Type II": {"A": 4},
            "Type III": {"A": 2},
            "Type IV": {"HT": 3},
            "Type V": {"A": 1}
        },
        "S": {
            "Type I": {"A": 12},
            "Type II": {"A": 5},
            "Type III": {"A": 3},
            "Type IV": {"HT": 4},
            "Type V": {"A": 2}
        }
    },
    "S-2": {
        "NS": {
            "Type I": {"A": 11, "B": 5},
            "Type II": {"A": 5},
            "Type III": {"A": 3},
            "Type IV": {"HT": 4},
            "Type V": {"A": 2}
        },
        "S": {
            "Type I": {"A": 12, "B": 6},
            "Type II": {"A": 6},
            "Type III": {"A": 4},
            "Type IV": {"HT": 5},
            "Type V": {"A": 3}
        }
    },
    "U": {
        "NS": {
            "Type I": {"A": 5},
            "Type II": {"A": 4},
            "Type III": {"A": 2},
            "Type IV": {"HT": 3},
            "Type V": {"A": 2}
        },
        "S": {
            "Type I": {"A": 6},
            "Type II": {"A": 5},
            "Type III": {"A": 3},
            "Type IV": {"HT": 4},
            "Type V": {"A": 3}
        }
    }
}

In [34]:
import rdflib
import pandas as pd
# Load RDF graph
rdf_graph = rdflib.Graph()
rdf_graph.parse("..\..\LBD files\smartReview\outputHotel Compliant Revit 2023 Advanced with Spaces.ifc.ttl", format="ttl")

In [110]:
# Getting Construction Type, Occupancy Group, & Sprinkler Type for the building
with open("..\..\SPARQL\storeyRule.sparql", "r") as file:
    sparql_query = file.read()

results = rdf_graph.query(sparql_query)

for result in results:
    construction_type = result.constructionType.toPython()
    occupancy_group = result.occupancyGroup.toPython()
    sprinkler_type = result.sprinklerType.toPython() if result.sprinklerType else "none"
    storey_num = result.storeyNumValue.toPython()

    # Splitting the construction type and subtype 
    if "-" in construction_type:
        main_construction_type, subtype = construction_type.rsplit("-", 1)
    else:
        main_construction_type = construction_type
        subtype = ""
if sprinkler_type != "none":
    sprinkler_system = "S" 
else: 
    sprinkler_system = "NS"
       
#print(main_construction_type, subtype, occupancy_group, sprinkler_system)

In [111]:
def findVal(table, occupancy_group, sprinkler_system, main_construction_type, subtype):
    height_limit = None  # Initialize height_limit to None before the loop

    # Iterate over all possible keys in the table
    for occupancy in table:
        # Split the key and check if occupancy_group is in the resulting list
        if occupancy_group in [o.strip() for o in occupancy.split(",")]:
            try:
                height_limit = table[occupancy][sprinkler_system][main_construction_type][subtype]
            except KeyError as e:
                print(f"KeyError: {e}")
                height_limit = None
            break

    return height_limit


#print(findVal(table_504_3, occupancy_group, sprinkler_system, main_construction_type, subtype))

In [112]:
# Function to check Value
def checkVal(val, allowableVal):
    if allowableVal is None:
        return "Value limit not found"
    
    val = int(val)
    allowableVal = int(allowableVal)
    
    if val <= allowableVal:
        return "Passed"
    else:
        return "Failed"

## Individual Occupancy Height Analysis
Each occupancy is checked to determine if the height of the occupancy exceeds the limits defined for the occupancy in Table 504.3. The results are presented in the following table:

In [113]:
with open("..\..\SPARQL\\areasSpaces.txt", "r") as file:
    sparql_query = file.read()

results = rdf_graph.query(sparql_query)

# Prepare data for the table
data = {
    "Story": [],
    "Revit ID": [],
    "Occupancy": [],
    "Name": [],
    "Height": [],
    "Allowable Height": [],
    "Height Result": []

}

# Process SPARQL results
for row in results:
    story = row["levelValue"]
    revit_id = row["id"]
    occupancy = str(row["occupancyClassification"])
    name = row["name"]
    height = float(row["storeyHeightValue"])  # Convert height to float
    allowable_height = findVal(table_504_3, occupancy, sprinkler_system, main_construction_type, subtype)
    height_result = checkVal(height, allowable_height)

    data["Story"].append(story)
    data["Revit ID"].append(revit_id)
    data["Occupancy"].append(occupancy)
    data["Name"].append(name)
    data["Height"].append(f"{height:.2f} ft")
    data["Allowable Height"].append(allowable_height)
    data["Height Result"].append(height_result)
    
    
df = pd.DataFrame(data)
df

,Story,Revit ID,Occupancy,Name,Height,Allowable Height,Height Result
0,01,32254,A-3,Ground Floor Gym,0.00 ft,70,Passed
1,01,32254,A-2,Ground Floor Banquet,0.00 ft,70,Passed
2,01,32254,A-2,Ground Floor Breakfast,0.00 ft,70,Passed
3,01,32254,A-3,Ground Floor Pool,0.00 ft,70,Passed
4,01,32254,R-1,Ground Floor Guest,0.00 ft,70,Passed
5,01,32254,B,Ground Floor Business,0.00 ft,70,Passed
6,04,32254,R-1,Fourth Floor,35.33 ft,70,Passed
7,03,32254,R-1,Third Floor,24.33 ft,70,Passed
8,02,32254,R-1,Second Floor,13.33 ft,70,Passed
9,01,32254,B,Ground Floor Public,0.00 ft,70,Passed

## Individual Occupancy Story Analysis
Each occupancy is checked to determine if the story location of the occupancy exceeds the limits defined for the occupancy in Table 504.4. The results are presented in the following table:

In [114]:
with open("..\..\SPARQL\\areasSpaces.txt", "r") as file:
    sparql_query = file.read()

results = rdf_graph.query(sparql_query)

# Prepare data for the table
data = {
    "Story": [],
    "Revit ID": [],
    "Occupancy": [],
    "Name": [],
    "Allowable Story": [],
    "Story Result": []

}

# Process SPARQL results
for row in results:
    story = str(row["levelValue"]).lstrip('0')  # Remove leading zeros
    revit_id = row["id"]
    occupancy = str(row["occupancyClassification"])
    name = row["name"]
    allowable_story = findVal(table_504_4, occupancy, sprinkler_system, main_construction_type, subtype)
    story_result = checkVal(story, allowable_story)

    data["Story"].append(story)
    data["Revit ID"].append(revit_id)
    data["Occupancy"].append(occupancy)
    data["Name"].append(name)
    data["Allowable Story"].append(allowable_story)
    data["Story Result"].append(story_result)
    
    
df = pd.DataFrame(data)
df

,Story,Revit ID,Occupancy,Name,Allowable Story,Story Result
0,1,32254,A-3,Ground Floor Gym,3,Passed
1,1,32254,A-2,Ground Floor Banquet,3,Passed
2,1,32254,A-2,Ground Floor Breakfast,3,Passed
3,1,32254,A-3,Ground Floor Pool,3,Passed
4,1,32254,R-1,Ground Floor Guest,4,Passed
5,1,32254,B,Ground Floor Business,4,Passed
6,4,32254,R-1,Fourth Floor,4,Passed
7,3,32254,R-1,Third Floor,4,Passed
8,2,32254,R-1,Second Floor,4,Passed
9,1,32254,B,Ground Floor Public,4,Passed

# Section 504.3 - Height in feet
## Building Code
The maximum height, in feet, of a building shall not exceed the limits specified in Table 504.3. 

**Exception**: Towers, spires, steeples and other roof structures shall be constructed of materials consistent with the required type of construction of the building except where other construction is permitted by Section 1510.2.5. Such structures shall not be used for habitation or storage. The structures shall be unlimited in height where of noncombustible materials and shall not extend more than 20 feet (6096 mm) above the allowable building height where of combustible materials (see Chapter 15 for additional requirements). 

### TABLE 504.3a ALLOWABLE BUILDING HEIGHT IN FEET ABOVE GRADE PLANE

In [92]:
# Table 504.3 Display
from IPython.display import display, HTML

rows = []

for occupancy_group, systems in table_504_3.items():
    for sprinkler_system, types in systems.items():
        for construction_type, subtypes in types.items():
            for subtype, height_limit in subtypes.items():
                rows.append({
                    "Occupancy Group": occupancy_group,
                    "Sprinkler System": sprinkler_system,
                    "Construction Type": construction_type,
                    "Subtype": subtype,
                    "Height Limit": height_limit
                })

df = pd.DataFrame(rows)

# Display the DataFrame as a scrollable table
def render_scrollable_table(dataframe, max_height=300):
    display(HTML(f"""
    <div style="max-height: {max_height}px; overflow-y: scroll;">
        {dataframe.to_html(index=False)}
    </div>
    """))

render_scrollable_table(df)

For SI: 1 foot = 304.8 mm.

**Note:**

- UL = Unlimited
- NS = Buildings not equipped throughout with an automatic sprinkler system
- S = Buildings equipped throughout with an automatic sprinkler system installed in accordance with Section 903.3.1.1
- S13R = Buildings equipped throughout with an automatic sprinkler system installed in accordance with Section 903.3.1.2

a. See Chapters 4 and 5 for specific exceptions to the allowable height in this chapter.

b. See Section 903.2 for the minimum thresholds for protection by an automatic sprinkler system for specific occupancies.

c. New Group H occupancies are required to be protected by an automatic sprinkler system in accordance with Section 903.2.5.

d. The NS value is only for use in evaluation of existing building height in accordance with the International Existing Building Code.

e. New Group I-1 and I-3 occupancies are required to be protected by an automatic sprinkler system in accordance with Section 903.2.6. For new Group I-1 occupancies Condition 1, see Exception 1 of Section 903.2.6.

f. New and existing Group I-2 occupancies are required to be protected by an automatic sprinkler system in accordance with Section 903.2.6 and Section 1103.5 of the International Fire Code.

g. For new Group I-4 occupancies, see Exceptions 2 and 3 of Section 903.2.6.

h. New Group R occupancies are required to be protected by an automatic sprinkler system in accordance with Section 903.2.8.

In [115]:
building_height = 57.33 #hardcoded value for now
allowed_building_height = findVal(table_504_3, occupancy_group, sprinkler_system, main_construction_type, subtype)
building_height_result = checkVal(building_height, allowed_building_height)

print(f"This section is considered: {building_height_result}")
if building_height_result == "Passed":
    passed5043 = "does not"
else: 
    passed5043 = "does"

print(f"\nThe building height of {building_height} ft {passed5043} exceed the limit of {allowed_building_height} ft as specified in Table 504.3 for:\n" \
                             f"• Occupancy - {occupancy_group},\n" \
                             f"• Construction Type - {main_construction_type},\n" \
                             f"• Subtype - {subtype},\n" \
                             f"• Sprinkler System - {sprinkler_type}.")

This section is considered: Passed

The building height of 57.33 ft does not exceed the limit of 70 ft as specified in Table 504.3 for:
• Occupancy - R-1,
• Construction Type - Type V,
• Subtype - A,
• Sprinkler System - 13.

The Exception allowing for increased heights for towers, spires, steeples, and other roof structures has not been implemented. Please verify this exception manually.

# Section 504.4 - Number of stories
## Building Code
The maximum number of stories of a building shall not exceed the limits specified in Table 504.4. 

### TABLE 504.4 ALLOWABLE NUMBER OF STORIES ABOVE GRADE PLANE

In [119]:
#Table 504.4 Display
rows = []

for occupancy_group, systems in table_504_4.items():
    for sprinkler_system, types in systems.items():
        for construction_type, subtypes in types.items():
            for subtype, height_limit in subtypes.items():
                rows.append({
                    "Occupancy Group": occupancy_group,
                    "Sprinkler System": sprinkler_system,
                    "Construction Type": construction_type,
                    "Subtype": subtype,
                    "Height Limit": height_limit
                })

df = pd.DataFrame(rows)

# Display the DataFrame as a scrollable table
def render_scrollable_table(dataframe, max_height=300):
    display(HTML(f"""
    <div style="max-height: {max_height}px; overflow-y: scroll;">
        {dataframe.to_html(index=False)}
    </div>
    """))

render_scrollable_table(df)

**Note**: 
- UL = Unlimited
- NP = Not Permitted
- NS = Buildings not equipped throughout with an automatic sprinkler system
- S = Buildings equipped throughout with an automatic sprinkler system installed in accordance with Section 903.3.1.1
- S13R = Buildings equipped throughout with an automatic sprinkler system installed in accordance with Section 903.3.1.2

---

a. See Chapters 4 and 5 for specific exceptions to the allowable height in this chapter.

b. See Section 903.2 for the minimum thresholds for protection by an automatic sprinkler system for specific occupancies.

c. New Group H occupancies are required to be protected by an automatic sprinkler system in accordance with Section 903.2.5.

d. The NS value is only for use in evaluation of existing building height in accordance with the International Existing Building Code.

e. New Group I-1 and I-3 occupancies are required to be protected by an automatic sprinkler system in accordance with Section 903.2.6. For new Group I-1 occupancies, Condition 1, see Exception 1 of Section 903.2.6.

f. New and existing Group I-2 occupancies are required to be protected by an automatic sprinkler system in accordance with Section 903.2.6 and Section 1103.5 of the International Fire Code.

g. For new Group I-4 occupancies, see Exceptions 2 and 3 of Section 903.2.6.

h. New Group R occupancies are required to be protected by an automatic sprinkler system in accordance with Section 903.2.8.

In [118]:
allowed_story = findVal(table_504_4, occupancy_group, sprinkler_system, main_construction_type, subtype)
story_num_result = checkVal(storey_num, allowable_story)

print(f"This section is considered: {story_num_result}")
if building_height_result == "Passed":
    passed5044 = "does not"
else: 
    passed5044 = "does"

print(f"\nThe building number of stories ({storey_num}) {passed5044} exceed the maximum allowed number of stories of ({allowed_story}) as specified in Table 504.4 for:\n" \
                             f"• Occupancy - {occupancy_group},\n" \
                             f"• Construction Type - {main_construction_type},\n" \
                             f"• Subtype - {subtype},\n" \
                             f"• Sprinkler System - {sprinkler_type}.")

This section is considered: Passed

The building number of stories (4) does not exceed the maximum allowed number of stories of (4) as specified in Table 504.4 for:
• Occupancy - R-1,
• Construction Type - Type V,
• Subtype - A,
• Sprinkler System - 13.